#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; verify_app_name "$APP"
IMAGE_TAG="$(get_running_image_tag "$APP")"
IMAGE=$(get_app_image_name "$APP" "$IMAGE_TAG")
DEST="$DOKKU_ROOT/$APP/nginx.conf.d/"

echo '-----> Copying nginx.conf.d files from image to app folder'
mkdir -p "$DEST"
copy_from_image "$IMAGE" "nginx.conf.d/." "$DEST" 2>/dev/null || true
